<a href="https://colab.research.google.com/github/goodmorninc-md/CVprojects/blob/main/(%E7%AC%AC%E4%B8%80%E8%8A%82%E8%AF%BE%E5%86%85%E5%AE%B9)Pytorch01_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01. PyTorch 基础知识
## PyTorch 是什么？
[PyTorch](https://pytorch.org/)是一个开源的机器学习和深度学习框架。
## PyTorch 能用来做什么？
PyTorch 允许你使用 Python 代码操作和处理数据并编写机器学习算法。
##谁在使用 PyTorch？
世界上许多最大的技术公司，如 [Meta (Facebook)](https://ai.facebook.com/blog/pytorch-builds-the-future-of-ai-and-machine-learning-at-facebook/)、特斯拉和微软，以及人工智能研究公司，如 [OpenAI 使用 PyTorch](https://openai.com/blog/openai-pytorch/) 来支持研究并将机器学习引入其产品。
PyTorch被广泛应用于工业和研究领域
例如，Andrej Karpathy（特斯拉的人工智能主管）曾多次发表演讲（[PyTorch DevCon 2019](https://youtu.be/oBklltKXtDE)、[特斯拉 2021 年人工智能日](https://youtu.be/j0z4FweCy4M?t=2904)），介绍特斯拉如何使用 PyTorch 为其自动驾驶计算机视觉模型提供动力。

### 为什么使用 PyTorch？
机器学习研究人员喜欢使用 PyTorch。截至 2023 年 12 月，PyTorch 是[Papers With Code 上使用最多的深度学习框架](https://paperswithcode.com/trends)，这是一个跟踪机器学习研究论文及其所附代码库的网站。
PyTorch 还能在幕后帮助你处理很多事情，比如 GPU 加速（让你的代码运行得更快）。
因此，你可以专注于操作数据和编写算法，PyTorch 会确保其快速运行。
如果特斯拉和 Meta（Facebook）等公司使用 PyTorch 构建模型，并将其部署到数百个应用程序、数千辆汽车和数十亿人面前，那么 PyTorch 显然也能胜任开发工作。

本节课涉及到的内容如下：

|**主题**|**内容**|
| ----- | ----- |
|**张量介绍**|张量是所有机器学习和深度学习的基本构件。|
|**创建张量** | 张量几乎可以表示任何类型的数据（图像、文字、数字表）。|
| **从张量中获取信息** | 如果你能将信息放入张量中，你也会想把它取出来。|
| **操纵张量** | 机器学习算法（如神经网络）涉及以多种不同方式操纵张量，如加法、乘法、组合等。|
| **处理张量形状** | 机器学习中最常见的问题之一是处理形状不匹配（试图将错误形状的张量与其他张量混合）。|
| **在张量上建立索引** | 如果你在 Python 列表或 NumPy 数组上建立过索引，那么它与张量非常相似，只不过张量的维度要多得多。
|**混合 PyTorch 张量和 NumPy**| PyTorch 使用张量（[`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)），NumPy 喜欢数组（[`np.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)），有时你会想混合和匹配它们。
| **可重复性**| 机器学习非常具有实验性，由于它使用大量*随机性*来工作，有时你会希望*随机性*不要那么随机。|
| **在 GPU 上运行张量** | GPU（图形处理器）能让你的代码更快，PyTorch 能让你在 GPU 上轻松运行代码。|


### Import Pytorch

In [230]:
import torch

In [231]:
torch.__version__

'2.2.1+cu121'

### 什么是张量(Tensor)

一张图片就可以是一个Tensor, [3, 224, 224] --> [colour_channels, height, width], pixels
3是指rbg,3*224*224层

计算机中不管是图片，还是视频，还是文本，归根到底，就是数字

### 创建一个tensor

#### Scalar

In [232]:
scalar = torch.tensor(6)  #0维的一个数字，可以看成一个标量

In [233]:
scalar

tensor(6)

In [234]:
scalar.ndim #看scalar的维度 n_dimension

0

In [235]:
a = 1
a

1

In [236]:
scalar_int = scalar.item()

In [237]:
scalar

# A. tensor(6)
# B. 6

tensor(6)

In [238]:
scalar_int

6

In [239]:
type(scalar_int)

int

#### Vector

In [240]:
# Vector 是 一维的Tensor

In [241]:
vector = torch.tensor([7, 7])

In [242]:
vector

tensor([7, 7])

In [243]:
vector.ndim

1

In [244]:
vector.shape

torch.Size([2])

In [245]:
vector = torch.tensor([[7, 7]])

In [246]:
vector.shape

torch.Size([1, 2])

#### Matrix

In [247]:
MATRIX = torch.tensor([[7,8],[9,10]])

In [248]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [249]:
MATRIX.ndim

2

In [250]:
MATRIX.shape

torch.Size([2, 2])

#### Tensor n>=3


In [251]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [252]:
TENSOR.shape  #最外层的中括号不用看，看每一层（直到最里层中括号）有多少个元素

torch.Size([1, 3, 3])

### Random Tensors

In [253]:
random_tensor = torch.rand(size=(3,4))

In [254]:
random_tensor

tensor([[0.4148, 0.9271, 0.4203, 0.3157],
        [0.2647, 0.7626, 0.7474, 0.1382],
        [0.0682, 0.6157, 0.6553, 0.6562]])

In [255]:
random_tensor.shape

torch.Size([3, 4])

In [256]:
random_tensor = torch.rand(size=(3,4))

In [257]:
random_tensor

tensor([[0.5310, 0.1103, 0.3368, 0.9681],
        [0.8205, 0.8183, 0.3061, 0.8058],
        [0.8653, 0.1961, 0.4908, 0.8624]])

In [258]:
random_image_size_tensor = torch.rand(size=(3,224,224))

In [259]:
random_image_size_tensor

tensor([[[0.2774, 0.4980, 0.4531,  ..., 0.0765, 0.8243, 0.7990],
         [0.3058, 0.8227, 0.6812,  ..., 0.2000, 0.5401, 0.2724],
         [0.8465, 0.3701, 0.4944,  ..., 0.8453, 0.2542, 0.6758],
         ...,
         [0.1297, 0.3321, 0.2141,  ..., 0.0570, 0.7292, 0.1909],
         [0.8205, 0.5774, 0.2676,  ..., 0.9902, 0.3087, 0.1581],
         [0.3308, 0.2183, 0.8310,  ..., 0.0574, 0.4852, 0.6464]],

        [[0.7753, 0.0538, 0.8131,  ..., 0.5042, 0.0860, 0.0645],
         [0.2495, 0.1170, 0.9119,  ..., 0.4525, 0.6792, 0.9947],
         [0.0027, 0.4502, 0.3105,  ..., 0.3335, 0.9545, 0.8679],
         ...,
         [0.1085, 0.6352, 0.1721,  ..., 0.8688, 0.9414, 0.5426],
         [0.7987, 0.9711, 0.1871,  ..., 0.3187, 0.8400, 0.8402],
         [0.8828, 0.0418, 0.6746,  ..., 0.9036, 0.5836, 0.0772]],

        [[0.4209, 0.8834, 0.3797,  ..., 0.5583, 0.9178, 0.8614],
         [0.7689, 0.1373, 0.3754,  ..., 0.5524, 0.2434, 0.7621],
         [0.5886, 0.9430, 0.9503,  ..., 0.0891, 0.6267, 0.

In [260]:
for _ in range(10):
  rand_tensor = torch.rand((10))  #生成的数都大于0
  randn_tensor = torch.randn(10)  #生成的数符合标准正态分布
  print(rand_tensor)
  print(randn_tensor)

tensor([0.5859, 0.5627, 0.7510, 0.9620, 0.1438, 0.0864, 0.4993, 0.6414, 0.9840,
        0.8416])
tensor([-0.4991, -0.8856, -0.5378,  0.2669,  0.9815,  1.1473, -0.9648,  0.2617,
        -1.0859,  0.7128])
tensor([0.6131, 0.6775, 0.9529, 0.1499, 0.5432, 0.4801, 0.2162, 0.1232, 0.4014,
        0.3152])
tensor([ 0.4302,  0.4839,  2.3135,  0.5313, -0.8276,  1.5721, -0.0623, -1.4502,
         1.4605, -0.5541])
tensor([0.0393, 0.3571, 0.9467, 0.2209, 0.4449, 0.2943, 0.9959, 0.0391, 0.7170,
        0.8279])
tensor([-1.1008,  0.7188,  1.0767,  0.7997,  0.6309,  0.7763, -0.5473,  1.1944,
        -0.3260, -0.8638])
tensor([0.1340, 0.8106, 0.8159, 0.0824, 0.1696, 0.7821, 0.4116, 0.3511, 0.6939,
        0.0909])
tensor([ 0.8234,  0.6193, -0.7181,  0.1328, -0.1360,  0.4459, -1.6081, -0.2750,
         1.0796, -0.9089])
tensor([0.3066, 0.0064, 0.8465, 0.7615, 0.7168, 0.0332, 0.6103, 0.3054, 0.8744,
        0.4205])
tensor([-1.4002,  0.7716, -0.7062,  1.4212,  2.2234, -1.1102,  1.1823, -0.1254,
       

### Tensor运算

In [261]:
tensor = torch.tensor([1,2,3])

In [262]:
tensor

tensor([1, 2, 3])

In [263]:
tensor = tensor + 10  #逐元素相加

In [264]:
tensor
# tensor(?)


tensor([11, 12, 13])

In [265]:
tensor = tensor * 10
tensor

tensor([110, 120, 130])

In [266]:
tensorA = torch.tensor([1,4,7])

In [267]:
tensorA.shape

torch.Size([3])

In [268]:
tensorB = torch.tensor([2,5,8])

In [269]:
tensorB * tensorA #对应元素相乘

tensor([ 2, 20, 56])

In [270]:
# Broadcast 广播机制

In [271]:
# 矩阵乘法 (a, b) (b, c)

In [272]:
tensorA @ tensorB

tensor(78)

In [273]:
MATRIXA = torch.tensor([[1,2],[3,4]])

In [274]:
MATRIXB = torch.tensor([[1,1],[1,2]])

In [275]:
MATRIXA.shape

torch.Size([2, 2])

In [276]:
MATRIXA @ MATRIXB

tensor([[ 3,  5],
        [ 7, 11]])

In [277]:
MATRIXA

tensor([[1, 2],
        [3, 4]])

In [278]:
MATRIXB

tensor([[1, 1],
        [1, 2]])

In [279]:
torch.matmul(MATRIXA, MATRIXB)

tensor([[ 3,  5],
        [ 7, 11]])

In [280]:
tensor = torch.rand(10000)

In [281]:
tensor

tensor([0.7793, 0.5621, 0.5838,  ..., 0.6906, 0.0405, 0.8163])

In [282]:
%%time

value = 0

for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 141 ms, sys: 0 ns, total: 141 ms
Wall time: 157 ms


tensor(3389.2021)

In [283]:
%%time  #使用pytorch内置矩阵乘法效率要比自己手算高

value = tensor @ tensor
value

UsageError: Can't use statement directly after '%%time'!


**如果你想实现某个功能（这个功能看起来是很基本的）， 不要自己实现， Google一下，你就知道**

In [284]:
tensor_A = torch.rand(3,4)

In [285]:
tensor_A.shape

torch.Size([3, 4])

In [286]:
tensor_A.T

tensor([[0.9552, 0.2267, 0.1174],
        [0.5347, 0.3298, 0.0607],
        [0.6461, 0.5642, 0.3587],
        [0.2896, 0.6306, 0.5459]])

In [287]:
tensor_A_reshape = tensor_A.reshape(2,6)

In [288]:
tensor_A

tensor([[0.9552, 0.5347, 0.6461, 0.2896],
        [0.2267, 0.3298, 0.5642, 0.6306],
        [0.1174, 0.0607, 0.3587, 0.5459]])

In [289]:
tensor_A_reshape

tensor([[0.9552, 0.5347, 0.6461, 0.2896, 0.2267, 0.3298],
        [0.5642, 0.6306, 0.1174, 0.0607, 0.3587, 0.5459]])

In [290]:
tensor_image_random = torch.rand(3,224,224)

In [291]:
tensor_re = tensor_image_random.reshape(-1,1,1) #224 224堆到一维，但还是三维，但后面俩1还存在

In [292]:
tensor_re.shape

torch.Size([150528, 1, 1])

In [293]:
tensor_sq = torch.squeeze(tensor_re)  #torch.squeeze降到一维了

In [294]:
tensor_sq.ndim

1

In [295]:
tensorC = torch.randint(1, 10, (3, 3))

In [296]:
tensorC

tensor([[8, 6, 4],
        [7, 9, 9],
        [1, 8, 3]])

In [297]:
value, indices = torch.max(tensorC, 1)  #在第一维度上求

In [298]:
value

tensor([8, 9, 8])

In [299]:
indices #最大值下标

tensor([0, 1, 1])

In [300]:
tensor = torch.arange(10, 101, 10)  #前两个是range，左闭右开，第三个是长度

In [301]:
tensor

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [302]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [303]:
TENSOR = torch.arange(1,10).reshape(1,3,3)

In [304]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [305]:
TENSOR.shape

torch.Size([1, 3, 3])

In [306]:
TENSOR[0,1,1] #与TENSOR[0][1][1]表示意思一样

tensor(5)

In [308]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [307]:
# [[1,2,3]] #要取到[1,2,3]，要保持和TENSOR.shape输出的torch.Size([1, 3, 3])对应的位置对齐
TENSOR[:,0]

tensor([[1, 2, 3]])

In [309]:
TENSOR[:,:,1]

tensor([[2, 5, 8]])

In [310]:
MATRIX = torch.arange(0,4).reshape(2,2)

In [311]:
MATRIX

tensor([[0, 1],
        [2, 3]])

In [312]:
MATRIX[0]

tensor([0, 1])

In [313]:
MATRIX[0,:]

tensor([0, 1])

In [314]:
MATRIX[:,0]

tensor([0, 2])

In [315]:
MATRIX[0,1]

tensor(1)

### 可移植性/可再现性/Reproducibility

In [316]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8983, 0.7911, 0.1960, 0.9054],
        [0.5236, 0.3232, 0.1204, 0.5062],
        [0.7753, 0.8666, 0.8832, 0.4887]])
tensor([[0.2452, 0.8486, 0.0528, 0.4261],
        [0.5238, 0.8116, 0.0723, 0.0744],
        [0.0599, 0.2436, 0.3261, 0.6776]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [317]:
## 计算机中一切的随机都是伪随机
torch.random.manual_seed(seed = 666)
random_tensor_C = torch.rand(3,4)

torch.random.manual_seed(seed = 666)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.3119, 0.2701, 0.1118, 0.1012],
        [0.1877, 0.0181, 0.3317, 0.0846],
        [0.5732, 0.0079, 0.2520, 0.5518]])
tensor([[0.3119, 0.2701, 0.1118, 0.1012],
        [0.1877, 0.0181, 0.3317, 0.0846],
        [0.5732, 0.0079, 0.2520, 0.5518]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [318]:
!nvidia-smi

Thu Mar 14 03:01:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [319]:
import torch
torch.cuda.is_available()

True

In [320]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [321]:
device

'cuda'

In [322]:
torch.cuda.device_count()

1

In [323]:
tensor = torch.tensor([1,2,3])

In [324]:
tensor.device

device(type='cpu')

In [326]:
!nvidia-smi


Thu Mar 14 03:02:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P0              28W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [328]:
import torch
torch.cuda.is_available()

True

cpu


In [330]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [332]:
tensor = torch.tensor([1,2,3])
print(tensor.device)
tensor = tensor.to(device)

cpu
